# Generated by Django 4.2 on 2024-12-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialization', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workers.team')),
            ],
        ),
    ]
